---
title: "Evaluación - B0305 LAB ECO GRAL 2025"
format: html
---

# Evaluación

El curso se aprueba con una nota igual o superior a 7.0. Las personas estudiantes con nota de 6.0 o 6.5 tienen derecho a hacer una prueba de ampliación. Si la nota es menor a 6.0 es insuficiente y no tiene derecho a prueba de ampliación, según el redondeo establecido en el artículo 25 del Reglamento de Régimen Académico Estudiantil. La evaluación del curso se hará de la siguiente forma:

## Evaluación global

| Evaluación                                                              | Puntaje               |
|------------------------------------------------------------------------|------------------------|
| 2 reportes en pareja de las prácticas de laboratorio*                  | 20 (10 por reporte)    |
| 2 reportes grupales de las prácticas de las giras                      | 25 (12.5 por reporte)  |
| Una presentación de la práctica grupal de la gira de Manú             | 10 (5 en Manú, 5 en UCR)|
| 1 presentación oral sobre la aplicación de una prueba estadística      | 10                     |
| 1 trabajo de investigación en parejas (Reporte y presentación)         | 35                     |
| **Total**                                                              | **100**                |

---

### Reportes de practicas

La evaluación de cada reporte se hará de la siguiente forma:

| Sección                 | Puntos |
|------------------------|--------|
| Título                 | 5      |
| Resumen                | 4      |
| Palabras claves        | 1      |
| Introducción           | 20     |
| Hipótesis y predicciones | 5    |
| Materiales y métodos   | 15     |
| Resultados             | 25     |
| Discusión              | 25     |
| Referencias            | 5      |
| **Total**              | **100**|

---

### Reportes semestrales
El proyecto de investigación en parejas (35% de la nota final) será evaluado de la siguiente forma:

| Sección            | Puntos |
|--------------------|--------|
| Anteproyecto       | 10     |
| Informe de avance  | 10     |
| Reporte            | 65     |
| Presentación oral  | 15     |
| **Total**          | **100**|

---

El anteproyecto se evaluará de la siguiente manera:

| Sección      | Puntos |
|-------------|--------|
| Título      | 5      |
| Introducción (incluye marco teórico, justificación, hipótesis y predicciones) | 40 |
| Materiales y métodos (incluye descripción del sitio de estudio, diseño experimental, equipo empleado y cronograma) | 50 |
| Referencias  | 5      |
| **Total**    | **100**|

---

El informe de avance se evaluará de la siguiente manera:

| Ítem                                                                                           | Puntos |
|------------------------------------------------------------------------------------------------|--------|
| Parte escrita:<br>- Las secciones del anteproyecto con las correcciones añadidas.<br>- Indicar modificaciones realizadas a la propuesta original.<br>- Resumen de datos preliminares: el número de eventos de muestreo y cantidad de muestras de los datos recolectados hasta el momento. | 55     |
| Cronograma de trabajo faltante:<br>- Explicación de la matriz de datos y de las modificaciones realizadas a la propuesta original y cronograma de trabajo faltante | 45     |
| **Total**                                                                                      | **100**|

---

El reporte de la investigación en parejas se evalúa siguiendo el siguiente cuadro de secciones:

| Sección              | Puntos |
|----------------------|--------|
| Título               | 4      |
| Resumen              | 5      |
| Palabras claves      | 1      |
| Introducción         | 25     |
| Materiales y métodos | 10     |
| Resultados           | 25     |
| Discusión            | 25     |
| Bibliografía         | 5      |
| **Total**            | **100**|

---

Las presentaciones orales se evalúan en base al uso del tiempo, orden, claridad, calidad y dominio, se entregará una rúbrica de calificación al inicio del semestre.

---

### Evaluación de colaboración

Para todos los reportes que se realicen de forma grupal y para la investigación en parejas se deberá entregar una evaluación de la colaboración de cada compañera o compañero del grupo, esto se tomará en cuenta para repartir la nota del reporte puesta por la persona docente de acuerdo con dicho criterio, según el siguiente cuadro:

| CONCEPTO                       | Porcentaje | Estudiante 1 | Estudiante 2 | Estudiante 3 | Estudiante 4 | Estudiante 5 |
|--------------------------------|------------|--------------|--------------|--------------|--------------|--------------|
| Planeamiento y diseño del proyecto |            |              |              |              |              |              |
| Recopilación de datos o información |          |              |              |              |              |              |
| Análisis e interpretación      |            |              |              |              |              |              |
| Redacción del reporte          |            |              |              |              |              |              |
| Carné de estudiante            |            |              |              |              |              |              |
| Firma de estudiante            |            |              |              |              |              |              |

---

## Entrega de evaluaciónes

La persona docente debe entregar al alumnado las evaluaciones calificadas y todo documento o material sujeto a evaluación, a más tardar diez días hábiles después de haberse efectuado las evaluaciones y haber recibido los documentos (Artículo 22 del Reglamento de Régimen Académico Estudiantil). El período razonable para guardar los trabajos y exámenes de los estudiantes posterior a la conclusión del ciclo lectivo es de seis meses, concluido este tiempo se pueden eliminar. Si la persona estudiante no está de acuerdo con la nota asignada en alguno de los rubros calificados, debe comunicarlo a los profesores del curso en un plazo no mayor de tres días hábiles posteriores a la devolución de esta. Los profesores atenderán con cuidado y prontitud la petición, para lo cual tendrá un plazo no mayor a cinco días hábiles (Artículo 22 del Reglamento de Régimen Académico Estudiantil).
---
title: "B0305 -- LAB ECO GRAL"
subtitle: "Año académico: 2025"
format: html
---

