---
title: "Metodología - B0305 LAB ECO GRAL 2025"
format: html
---

# Metodología

Durante el curso se harán 4 prácticas de laboratorio, dos de ellas en el campus UCR y dos durante las dos giras. Se hará un trabajo práctico de investigación en parejas a lo largo de todo el semestre. Además, se deberá explicar los objetivos y mecánica de una prueba estadística durante una sesión de laboratorio. Todas las actividades del curso son de asistencia obligatoria. **Solo se pueden justificar dos ausencias a clases**, prácticas o giras en conjunto, siguiendo los criterios del Artículo 24 del Reglamento del Régimen Académico Estudiantil, **si se falta una tercera vez se pierde el curso.** 

## Prácticas de laboratorio del curso

La teoría y las técnicas o herramientas de análisis para cada práctica se exponen en el aula y se les facilita a las personas estudiantes material escrito para repaso. Algunas prácticas podrán ser establecidas por las personas docentes mientras que otras se plantearán en conjunto entre las personas estudiantes, los docentes y los asistentes académicos del curso. Los datos se recolectan en la(s) siguiente(s) semana(s) y luego se analizan, según sea el caso. Para cada práctica las personas estudiantes cuentan con una guía y una lectura de referencia que deben estudiar antes de la ejecución de la práctica. 

En cada práctica las personas estudiantes deben participar en el planeamiento, la colecta y el análisis de datos, así como en la elaboración de un reporte científico. Si él o la estudiante se ausenta de algún laboratorio sin la debida justificación, no podrá presentar el reporte de la práctica correspondiente. Para cada práctica las personas estudiantes deben hacer un reporte de acuerdo con el formato solicitado en el curso y deberán de subirlo al entorno del curso en Mediación Virtual, al inicio de la clase en la fecha de entrega según el cronograma; la puntualidad en la entrega de los reportes es estricta, **no se aceptan reportes después de la fecha establecida.** **Para el primer reporte la persona estudiante obtendrá una calificación preliminar, y deberá corregirlo y presentarlo de nuevo. El puntaje que reciba en la segunda revisión corresponderá a la calificación final de la primera práctica.** En la sección de evaluación viene el desglose de la calificación de cada informe (son cuatro informes en pareja o grupales según corresponda, más el informe del proyecto semestral que se elabora a lo largo del semestre)

## Prácticas grupales en las giras

El curso tiene además dos giras (una de un día, la otra de 2 noches 3 días) en las que se realizan prácticas grupales. **En la primera gira (Bosque Municipal de Atenas) los y las estudiantes ayudan a estudiar una pregunta propuesta por una persona docente o asistente. En la segunda gira cada grupo de estudiantes plantea una pregunta para estudiar y lleva a cabo el proceso de investigación; siendo responsables de conseguir los materiales y el equipo necesario para lograr el éxito del proyecto durante la gira.** Los datos de la gira se colectan y se escriben en grupo. Además, durante la gira se hará una presentación oral 10 min con los resultados preliminares. A la semana siguiente se realiza la presentación (10 min + 5 min preguntas) de los resultados con el análisis de datos final (consejo: tener 12 diapositivas máximo). Todas las personas estudiantes del grupo serán responsables de la toma de los datos, su procesamiento e interpretación, así como de la elaboración del reporte y presentación oral. Por lo anterior, hay un formulario para establecer el grado de participación, que deben entregar firmado junto al informe (ver sección de Evaluación). En todas las giras y las prácticas se deben respetar y acatar las normas establecidas en el Reglamento Universitario y de las instalaciones donde se realiza la gira (ver infografía al final de este documento). Durante las giras y las prácticas de campo los estudiantes deben seguir las normas de seguridad para trabajo en el campo que se les indique. Las fechas y los destinos de las giras se encuentran en el cronograma. 

## Trabajo Práctico de Investigación en parejas

Como parte del curso, las personas estudiantes deben realizar un trabajo práctico de investigación en parejas. En este trabajo las y los estudiantes deben poner en práctica todos los pasos del método científico con un problema o pregunta ecológica. **No se permitirán trabajos cortos, deben ser de tres o más visitas de campo o incluir un componente de laboratorio de una complejidad razonable, dependiendo de la naturaleza del proyecto.** Dentro del primer mes de clases (agosto) los y las estudiantes deben presentar su idea mediante un anteproyecto escrito. El anteproyecto escrito deberá llevar el siguiente formato: título, introducción (incluyendo hipótesis y predicciones), materiales y métodos y bibliografía. En la introducción los estudiantes deberán incluir una breve revisión de la literatura que sirva para justificar las hipótesis que quieren probar y sus predicciones. Los materiales y métodos deberán incluir una descripción del sitio de estudio, del diseño experimental (diseño de muestreo) y de los materiales que usarán para ello, las posibles pruebas estadísticas y un cronograma que incluya las fechas de recolección de datos y análisis de datos.

En los siguientes dos meses (setiembre y octubre) los estudiantes deben llevar a cabo la recolección de datos. **Se les solicitará un informe de avance a mitad del mes de octubre.** En el último mes (noviembre) deben concluir con la toma de datos y entrar en el análisis de los datos y preparar el reporte y la presentación oral. El documento deberá llevar el formato de reporte científico según el formato que se les entregue en el curso. Los estudiantes deben presentar los resultados en forma oral al final del curso. La presentación de los trabajos orales se realizará según la fecha indicada en el cronograma. Todas las personas estudiantes deberán presentarse a la hora establecida. Para cada trabajo semestral las y los estudiantes tienen un tiempo de 12 min de presentación y 5 min para aclarar preguntas del público.
---
title: "B0305 -- LAB ECO GRAL"
subtitle: "Año académico: 2025"
format: html
---

