---
title: "B0305 -- LAB ECO GRAL"
subtitle: "Año académico: 2025"
format: html
---

# Literatura

* Begon, M., Harper, J., y Townsend, C. (2006). Ecology: From individuals to ecosystems
(4a. ed.). Blackwell.

* Beckerman, A. P., Childs, D. Z., & Petchey, O. L. (2017). Getting started with R: an
introduction for biologists. Oxford University Press.

* Brower, J. E., Zar, J. H., & Von Ende, C. N. (1998). Field and laboratory methods for general
ecology (Vol. 4, pp. 25-51). Boston: WCB McGraw-Hill.

* Crawley, M. J. (2007) The R Book. John Wiley.

* Farji-Brenner, A. (2003). Uso correcto, parcial e incorrecto de los términos "hipótesis" y "predicciones" en ecología. Asociación Argentina de Ecología. <a href="../references/Farji-Brenner-2003.pdf" target="_blank">PDF</a>

* Gotelli, N. J., & Ellison, A. M. (2004). A primer of ecological statistics (Vol. 1, pp. 1-640). Sunderland: Sinauer Associates. Chapter 4: Framing and testing hypotheses. <a href="../references/Gotelli-2004-cap-4.pdf" target="_blank">PDF</a>

* Gotelli, N. J., & Ellison, A. M. (2004). A primer of ecological statistics (Vol. 1, pp. 1-640). Sunderland: Sinauer Associates. Chapter 6: Designing Successful Field Studies. <a href="../references/Gotelli-2004-cap-6.pdf" target="_blank">PDF</a>

* Krebs, C. J. (1999). Ecological Methodology (2a ed.). Benjamin Cummings, Inc.
<a href="http://www.zoology.ubc.ca/~krebs/books.html" target="_blank">Link</a>

* Quinn, G. P. y Keough, M. J. (2002). Experimental design and data analysis for
biologists. Cambridge University Press.

* Schimel, J. (2012). Writing science: how to write papers that get cited and proposals
that get funded. Oxford University Press USA.

* Sutherland, W. J. (Ed.). (2006). Ecological census techniques: a handbook. Cambridge
university press. <a href="https://www.researchgate.net/publication/273070581_Ecological_Census_Techniques_A_Handbook" target="_blank" >Link</a>