---
title: "B0305 -- LAB ECO GRAL"
subtitle: "Año académico: 2025"
format: html
---

## Cronograma

- **Semana 1 (15/8):** Feriado día de la Madre.

<details open>
<summary><strong>Práctica 1</strong></summary>

- **Semana 2 (22/8):** 
  - Introducción al curso.
  - Organismos y ambiente.  
  - Definición de la pregunta práctica 1. 
  - Observación, pregunta e hipótesis.
- **Semana 3 (29/8):** 
  - Definición de los métodos. 
  - Introducción a la escritura de reportes y análisis de datos en ecología. 
  - Discusión métodos práctica 1.
- **Semana 4 (5/9):** 
  - Recolecta de datos. 
  - 💡Anteproyecto semestral. 
- **Semana 5 (12/9):** 
  - Análisis de datos.

</details>


<details open>
<summary><strong>Práctica 2</strong></summary>

- **Semana 6 (19/9):**
  - Poblaciones.
  - Definición de la pregunta sobre poblaciones enfocada en Bosque Municipal Atenas.
  - Métodos.
  - 🕒 Entrega: Reporte 1 versión 1.
- **Semana 7 (26/9):**
  - Métodos/recolecta de datos práctica 2.
  - Recolecta de datos Gira 1 Bosque Municipal de Atenas.
  - Profes y asistentes entregan Reporte 1 revisado.
- **Semana 8 (3/10):**
  - Análisis de datos poblaciones práctica 1.
  - 🕒 Entrega final reporte 1.

</details>


<details open>
<summary><strong>Práctica 3</strong></summary>

- **Semana 9 (10/10):**
  - Interacciones Depredación.
  - Pregunta/Métodos.
  - 🕒 Entrega: Reporte 2.
- **Semana 10 (17/10):**
  - Setup de experimento práctica 3.
- **Semana 11 (24/10):**
  - Recolecta de datos.
  - 💡 🕒 Entrega: Avance 1 proyecto semestral.
- **Semana 12 (31/10):**
  - Análisis de datos.

</details>


<details open>
<summary><strong>Práctica 4</strong></summary>

- **Semana 13 (7/11):**
  - Ecosistemas.
  - Pregunta grupal Manú.
  - 🕒 Entrega: Reporte 3.
- **Semana 14 (14/11):**
  - Métodos/Recolección de datos.
  - Gira 2 Manú, 14–16 nov.
  - Avance 2 (Datos).
- **Semana 15 (21/11):**
  - Análisis de datos Gira Manú.
- **Semana 16 (28/11):**
  - Presentaciones orales Gira Manú.
  - 🕒 Entrega: Reporte 4.

</details>

<summary><strong>Proyecto Semestral y Otros</strong></summary>

- **Semana 17 (5/12):**
  - 💡Presentaciones orales Proyecto semestral.
  - 💡🕒 Entrega: Informe escrito Proyecto semestral.


