---
title: "B0305 - LABORATORIO DE ECOLOG칈A GENERAL"
toc: true
toc-depth: 4
format:
  html:
    toc-title: "En esta pagina"
    # include-before-body: helpers/remove-nav.html
    # include-after-body: helpers/remove-title.html
---

# 游늼 Laboratorio de Ecolog칤a General 

**Selecciona A침o/Periodo Acad칠mico:**


<a href="2025/index.qmd">
    <button class="button-61">2025</button>
</a>


## Introduccion

La ecolog칤a es una ciencia integradora de una amplia gama de ramas de la
biolog칤a. Definida originalmente por Ernest Haeckel (1834-1919) como el estudio de
las interacciones entre los organismos y el ambiente, la definici칩n de ecolog칤a se
ampl칤a en la actualidad a estudiar c칩mo esas interacciones afectan la distribuci칩n y
la abundancia de las especies y el funcionamiento del ecosistema.

Esta definici칩n implica una variedad de procesos por estudiar. El ambiente de
un organismo contempla desde lo m치s obvio como las caracter칤sticas f칤sicas del
entorno y de otros organismos, hasta lo no tan obvio como el ambiente celular o
gen칠tico en el que tienen su desarrollo. Las interacciones, definidas como el
intercambio de materia y energ칤a o la interferencia en esta transferencia, pueden
darse a diferentes escalas, como por ejemplo entre organismos, entre organismos y
ambientes (dentro de ecosistemas) o entre ecosistemas. Los ecosistemas a su vez
pueden delimitarse seg칰n nuestro inter칠s, desde el ecosistema dentro del intestino
de un animal hasta incluso todo nuestro planeta. Esto nos lleva a una inmensa
cantidad de mecanismos y procesos que pueden ser estudiados dentro del campo de
la ecolog칤a y que son necesarios para entender el funcionamiento de los ecosistemas.
As칤, en la ecolog칤a se pueden estudiar los organismos a nivel de individuo, poblaci칩n
y comunidad, su asociaci칩n con el ambiente y su participaci칩n (funci칩n) dentro del
ecosistema.

El desarrollo de la ecolog칤a se realiza principalmente mediante el m칠todo
cient칤fico llamado hipot칠tico-deductivo. Esto involucra la observaci칩n de patrones en
la naturaleza, la formulaci칩n de hip칩tesis que expliquen estas observaciones, la
formulaci칩n de predicciones que se basen en el cumplimiento de las hip칩tesis, el
dise침o de experimentos que permitan probar las hip칩tesis con el an치lisis de los
datos generados por los experimentos. Finalmente, si los resultados concuerdan con
las predicciones se deduce que hay un apoyo a no rechazar la hip칩tesis propuesta.

Estos pasos implican que las personas estudiantes de la ecolog칤a ser치n
capaces de dise침ar experimentos que no sean ambiguos y pongan a prueba las
hip칩tesis previamente generadas. Adem치s, deber치n desarrollar destrezas para la
toma de datos de campo y de laboratorio, y tener conocimiento de t칠cnicas
estad칤sticas para analizar los datos y de lo que previamente se ha publicado sobre el
tema que se est치 estudiando. Como toda ciencia, la ecolog칤a avanza si nuestros
resultados son divulgados, por ende parte del conocimiento que deber치n tener las
personas estudiantes ser치 saber transmitir sus resultados y explicaciones por
manuscritos y exposiciones orales.

### Descripci칩n y objetivos del curso

El Laboratorio de Ecolog칤a General complementa la teor칤a con pr치cticas en el campo
y el laboratorio. Al finalizar el curso de laboratorio de Ecolog칤a General se espera que
la persona estudiante sea capaz de realizar las actividades mencionadas a
continuaci칩n:

### Objetivo general

Desarrollar habilidades para plantear, dise침ar y ejecutar investigaciones de campo y
laboratorio en ecolog칤a tropical, con 칠nfasis en la prueba de hip칩tesis por medio del
m칠todo cient칤fico. Ser capaz de realizar investigaciones que lleven a la pr치ctica
conceptos te칩ricos aprendidos en el curso de teor칤a.

### Objetivos espec칤ficos

1. Formular hip칩tesis biol칩gicas y predicciones para el estudio de un patr칩n
observado en la naturaleza o le칤do en la literatura.
2. Plantear investigaciones en campo y laboratorio mediante la aplicaci칩n del
dise침o experimental y la prueba de hip칩tesis ecol칩gicas.
3. Realizar an치lisis estad칤sticos y redactar informes cient칤ficos.

### Conocimientos

* Hip칩tesis y predicciones
* Componentes b치sicos de un dise침o experimental
* Pruebas estad칤sticas b치sicas
* Principios de operaci칩n de equipo b치sico de investigaci칩n ecol칩gica
* Formato y secciones de un art칤culo cient칤fico
* Buscar, comprender, analizar y citar correctamente la literatura cient칤fica

### Habilidades

* Capacidad de observaci칩n cient칤fica
* Formular hip칩tesis biol칩gicas y predicciones para el estudio de un patr칩n observado en la naturaleza o le칤do en la literatura
* Planteamiento, dise침o experimental y ejecuci칩n de investigaciones en campo y laboratorio para poner a prueba hip칩tesis ecol칩gicas
* Uso de equipo b치sico de investigaci칩n ecol칩gica
* Habilidades b치sicas de muestreo ecol칩gico: p.ej. cuadrantes, transectos, muestreo aleatorio vs. sistem치tico
* Manejo, depuraci칩n y control de calidad de datos ecol칩gicos
* An치lisis estad칤stico: saber cu치ndo y por qu칠 usar t de student, Chi-cuadrado, ANOVA, ANCOVA, regresi칩n lineal y correlaci칩n
* Uso de R para manipulaci칩n y graficaci칩n de datos y an치lisis estad칤stico
* An치lisis e interpretaci칩n de resultados cient칤ficos para generar nuevo conocimiento
* Redacci칩n de manuscritos cient칤ficos
* Dar presentaciones orales
* Realizar revisi칩n de literatura

### Aptitudes

* Habilidad de trabajar en equipo y colaborar
* 칄tica cient칤fica (qu칠 constituye el plagio y c칩mo evitarlo)
* 칄tica en la recolecci칩n y manejo de datos
* Compromiso y dedicaci칩n para cumplir metas y completar la recolecta de datos
* Curiosidad cient칤fica
* Evaluaci칩n y reducci칩n del riesgo durante el trabajo campo

## Metodolog칤a

Durante el curso se har치n dos pr치cticas de laboratorio, dos pr치cticas durante giras, y
un trabajo pr치ctico de investigaci칩n en parejas a lo largo de todo el semestre. Los
estudiantes entregar치n cinco informes escritos. Adicionalmente, para las dos
pr치cticas de gira y el trabajo de investigaci칩n en parejas deben de realizar una
presentaci칩n oral. Todas las actividades del curso son de asistencia obligatoria. Solo
se pueden justificar dos ausencias a clases, pr치cticas o giras en conjunto, siguiendo
los criterios del Art칤culo 24 del Reglamento del R칠gimen Acad칠mico Estudiantil, si se
falta una tercera vez se pierde el curso.

### Pr치cticas de laboratorio y de gira

Todas las pr치cticas de laboratorio y gira se planean en conjunto entre las
personas estudiantes, docentes y asistentes del curso en el aula. Los datos se
recolectan en la siguiente semana ya sea en el campus o en las giras, y luego se
dedica una sesi칩n adicional en el aula a ayudar a los grupos con el an치lisis
estad칤stico. Cada grupo de estudiantes tendr치 5-6 integrantes. Para cada pr치ctica de
laboratorio y gira las personas estudiantes contar치n con lecturas de referencia que
deben estudiar antes de la sesi칩n de planeamiento. En cada pr치ctica los y las
estudiantes deben participar en el planeamiento, la toma y el an치lisis de los datos,
mientra que el informe escrito se realiza de forma individual. Las presentaciones
orales para las pr치cticas de giras y el trabajo en parejas deben durar 12 minutos
m치s 5 minutos de preguntas. Un m치ximo de dos personas presentan y las dem치s
contestan preguntas. Hay un formulario para establecer el grado de participaci칩n,
que deben entregar firmado junto al informe (ver secci칩n de Evaluaci칩n).

Si el o la estudiante se ausenta de alg칰n laboratorio sin la debida justificaci칩n,
no podr치 presentar el informe de la pr치ctica correspondiente. El informe se hace de
acuerdo al formato solicitado en el curso (ver abajo) y deber치n de subirlo al entorno
del curso en Mediaci칩n Virtual, al inicio de la clase en la fecha de entrega seg칰n el
cronograma; la puntualidad en la entrega de los manuscritos es estricta, no se
aceptan manuscritos despu칠s de la fecha establecida.

En todas las giras y las pr치cticas se deben respetar y acatar las normas
establecidas en el Reglamento Universitario y de las instalaciones donde se realiza la
gira (ver infograf칤a al final de este documento). Durante las giras y las pr치cticas de
campo los estudiantes deben seguir las normas de seguridad para trabajo en el
campo que se les indique. Las fechas y los destinos de las giras se encuentran en el
cronograma.

### Investigaci칩n en parejas

Como parte del curso las personas estudiantes deben realizar un trabajo pr치ctico de
investigaci칩n en parejas. En este trabajo las y los estudiantes deben poner en
pr치ctica todos los pasos del m칠todo cient칤fico con un problema o pregunta ecol칩gica.
No se permitir치n trabajos cortos, deben ser de tres o m치s visitas de campo,
dependiendo de la naturaleza del proyecto. En la segunda semana los y las
estudiantes deben presentar su idea mediante una introducci칩n escrita. Esta
introducci칩n deber치 llevar el siguiente formato: t칤tulo del proyecto, observaci칩n de
campo o de la literatura que motiva la investigaci칩n, pregunta de investigaci칩n,
hip칩tesis, predicciones, y bibliograf칤a. En la introducci칩n los estudiantes deber치n
incluir una breve revisi칩n de la literatura que sirva para justificar las hip칩tesis que
quieren probar y sus predicciones. En la semana 6 las personas estudiantes deber치n
entregar materiales, m칠todos y bibliograf칤a. Los materiales y m칠todos deber치n
incluir una descripci칩n del sitio de estudio, del dise침o experimental (dise침o de
muestreo) y de los materiales que usar치n para ello, las posibles pruebas estad칤sticas,
un cronograma que incluya las fechas de recolecci칩n y an치lisis de datos, y un
desglose de costos.

En los siguientes dos meses los estudiantes deben llevar a cabo la
recolecci칩n de datos. Se les solicitar치n dos informes de avances, uno en la semana
10 y otro en la 13. En el 칰ltimo mes (noviembre) deben concluir con la toma de
datos y entrar en el an치lisis de los datos y preparar el manuscrito y la presentaci칩n
oral. El documento deber치 llevar el formato de manuscrito cient칤fico seg칰n el
formato que se les entregue en el curso. Los estudiantes deben presentar los
resultados en forma oral al final del curso. La presentaci칩n de los trabajos orales se
realizar치 seg칰n la fecha indicada en el cronograma en un mini-simposio abierto al
p칰blico. Todas las personas estudiantes deber치n presentarse a la hora establecida.
Para cada trabajo las y los estudiantes tienen un tiempo de 12 minutos de
presentaci칩n y 5 minutos para aclarar preguntas del p칰blico

## Evaluaci칩n

El curso se aprueba con una nota igual o superior a 7.0. Las personas
estudiantes con nota de 6.0 o 6.5 tienen derecho a hacer una prueba de ampliaci칩n.
Si la nota es menor a 6.0 es insuficiente y no tiene derecho a prueba de ampliaci칩n,
seg칰n el redondeo establecido en el art칤culo 25 del Reglamento de R칠gimen
Acad칠mico Estudiantil. La evaluaci칩n del curso se har치 de la siguiente forma:

| Evaluaci칩n           | Valor (%) | Informe escrito | Presentaci칩n oral |
|----------------------|-----------|------------------|--------------------|
| Informe 1            | 10        | 10               |                    |
| Informe 2            | 20        | 15               | 5                  |
| Informe 3            | 20        | 20               |                    |
| Informe 4            | 20        | 15               | 5                  |
| Trabajo en parejas   | 30        | 20               | 10                 |
| **Total**            | **100**   | **80**           | **20**             |

---

Todos los informes escritos se eval칰an de acuerdo al siguiente esquema, y se
brindar치n r칰bricas de evaluaci칩n m치s detalladas para estandarizar la revisi칩n por
parte de asistentes y profesores.

| Secci칩n                           | Valor (%) |
|----------------------------------|-----------|
| T칤tulo, resumen y palabras clave | 10        |
| Introducci칩n                     | 10        |
| Hip칩tesis y predicciones         | 10        |
| Materiales y m칠todos             | 20        |
| Resultados                       | 25        |
| Discusi칩n                        | 15        |
| Referencias                      | 10        |
| **Total**                        | **100**   |


--- 

Las presentaciones orales se eval칰an de acuerdo a estos criterios y tambi칠n se
brindar치 una r칰brica detallada de calificaci칩n

| Secci칩n                             | Valor (%) |
|------------------------------------|-----------|
| Introducci칩n                       | 25        |
| M칠todos y resultados               | 25        |
| Discusi칩n                          | 20        |
| Calidad general de la presentaci칩n | 30        |
| **Total**                          | **100**   |

---

La persona docente debe entregar al alumnado las evaluaciones calificadas y todo
documento o material sujeto a evaluaci칩n, a m치s tardar diez d칤as h치biles despu칠s de
haberse efectuado las evaluaciones y haber recibido los documentos (Art칤culo 22 del
Reglamento de R칠gimen Acad칠mico Estudiantil). El per칤odo de tiempo razonable
para guardar los trabajos y ex치menes de los estudiantes posterior a la conclusi칩n del
ciclo lectivo es de seis meses, concluido este tiempo se pueden eliminar. Si la
persona estudiante no est치 de acuerdo con la nota asignada en alguno de los rubros
calificados, debe comunicarlo a la coordinadora del curso en un plazo no mayor de
tres d칤as h치biles posteriores a la devoluci칩n de esta. La coordinadora atender치 con
cuidado y prontitud la petici칩n, para lo cual tendr치 un plazo no mayor a cinco d칤as
h치biles (Art칤culo 22 del Reglamento de R칠gimen Acad칠mico Estudiantil).


## Chronograma del curso

  <table class="syllabus">
    <thead>
      <tr>
        <th>Sem.</th>
        <th>Fecha</th>
        <th>Pr치ctica</th>
        <th>Tema</th>
        <th>Sesi칩n</th>
        <th>Entregas / Giras</th>
        <th>Trabajo Final</th>
      </tr>
    </thead>
    <tbody>
      <tr class="odd">
        <td>1</td>
        <td>15/8</td>
        <td>1</td>
        <td>Organismos y ambiente</td>
        <td>Pregunta</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="even">
        <td>2</td>
        <td>23/8</td>
        <td>1</td>
        <td>M칠todos</td>
        <td>Observaci칩n, pregunta e hip칩tesis</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>3</td>
        <td>30/8</td>
        <td>1</td>
        <td></td>
        <td>Recolecta datos</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="even">
        <td>4</td>
        <td>6/9</td>
        <td>1</td>
        <td></td>
        <td>An치lisis</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>5</td>
        <td>13/9</td>
        <td>2</td>
        <td>Poblaciones</td>
        <td>Pregunta</td>
        <td>Informe 1</td>
        <td></td>
      </tr>
      <tr class="even">
        <td>6</td>
        <td>20/9</td>
        <td>2</td>
        <td></td>
        <td>M칠todos / recolecta de datos</td>
        <td>Gira 1: M칠todos</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>7</td>
        <td>27/9</td>
        <td>2</td>
        <td></td>
        <td>An치lisis</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="even">
        <td>8</td>
        <td>4/10</td>
        <td>3</td>
        <td>Interacciones</td>
        <td>Pregunta / M칠todos</td>
        <td>Informe 2</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>9</td>
        <td>11/10</td>
        <td>3</td>
        <td></td>
        <td>Setup de experimento</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="even">
        <td>10</td>
        <td>18/10</td>
        <td>3</td>
        <td></td>
        <td>Recolecta de datos</td>
        <td></td>
        <td>Avance 1</td>
      </tr>
      <tr class="odd">
        <td>11</td>
        <td>25/10</td>
        <td>3</td>
        <td></td>
        <td>An치lisis</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="even">
        <td>12</td>
        <td>1/11</td>
        <td>4</td>
        <td>Ecosistemas</td>
        <td>Pregunta</td>
        <td>Informe 3</td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>13</td>
        <td>8/11</td>
        <td>4</td>
        <td></td>
        <td>M칠todos / Recolecta de datos</td>
        <td>Gira 2</td>
        <td>Avance 2 (Datos)</td>
      </tr>
      <tr class="even">
        <td>14</td>
        <td>15/11</td>
        <td>4</td>
        <td></td>
        <td>An치lisis</td>
        <td></td>
        <td></td>
      </tr>
      <tr class="odd">
        <td>15</td>
        <td>22/11</td>
        <td></td>
        <td></td>
        <td></td>
        <td>Informe 4</td>
        <td>Informe escrito</td>
      </tr>
      <tr class="even">
        <td>16</td>
        <td>29/11</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>Presentaciones orales</td>
      </tr>
    </tbody>
  </table>


-----------------



